/*
Deployment script for GPData

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar RunAutomatedScripts "false"
:setvar DatabaseName "GPData"
:setvar DefaultFilePrefix "GPData"
:setvar DefaultDataPath "/var/opt/mssql/data/"
:setvar DefaultLogPath "/var/opt/mssql/data/"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO

IF (DB_ID(N'$(DatabaseName)') IS NOT NULL)
BEGIN
    DECLARE @rc      int,                       -- return code
            @fn      nvarchar(4000),            -- file name for back up
            @dir     nvarchar(4000)             -- backup directory

    EXEC @rc = [master].[dbo].[xp_instance_regread] N'HKEY_LOCAL_MACHINE', N'Software\Microsoft\MSSQLServer\MSSQLServer', N'BackupDirectory', @dir output, 'no_output'
    if (@rc = 0) SELECT @dir = @dir + N'\'

    IF (@dir IS NULL)
    BEGIN 
        EXEC @rc = [master].[dbo].[xp_instance_regread] N'HKEY_LOCAL_MACHINE', N'Software\Microsoft\MSSQLServer\MSSQLServer', N'DefaultData', @dir output, 'no_output'
        if (@rc = 0) SELECT @dir = @dir + N'\'
    END

    IF (@dir IS NULL)
    BEGIN
        EXEC @rc = [master].[dbo].[xp_instance_regread] N'HKEY_LOCAL_MACHINE', N'Software\Microsoft\MSSQLServer\Setup', N'SQLDataRoot', @dir output, 'no_output'
        if (@rc = 0) SELECT @dir = @dir + N'\Backup\'
    END

    IF (@dir IS NULL)
    BEGIN
        SELECT @dir = N'$(DefaultDataPath)'
    END

    SELECT  @fn = @dir + N'$(DatabaseName)' + N'-' + 
            CONVERT(nchar(8), GETDATE(), 112) + N'-' + 
            RIGHT(N'0' + RTRIM(CONVERT(nchar(2), DATEPART(hh, GETDATE()))), 2) + 
            RIGHT(N'0' + RTRIM(CONVERT(nchar(2), DATEPART(mi, getdate()))), 2) + 
            RIGHT(N'0' + RTRIM(CONVERT(nchar(2), DATEPART(ss, getdate()))), 2) + 
            N'.bak' 
            BACKUP DATABASE [$(DatabaseName)] TO DISK = @fn
END
GO
USE [$(DatabaseName)];


GO
<<<<<<< Updated upstream
PRINT N'Dropping Foreign Key [dbo].[FK__Condition__Subje__40F9A68C]...';


GO
ALTER TABLE [dbo].[Condition] DROP CONSTRAINT [FK__Condition__Subje__40F9A68C];


GO
PRINT N'Dropping Foreign Key [dbo].[FK__Condition__Ident__3D2915A8]...';


GO
ALTER TABLE [dbo].[Condition] DROP CONSTRAINT [FK__Condition__Ident__3D2915A8];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_Condition_RelatedClinicalConditions_Condition]...';


GO
ALTER TABLE [dbo].[Condition_RelatedClinicalConditions] DROP CONSTRAINT [FK_Condition_RelatedClinicalConditions_Condition];


GO
PRINT N'Dropping Foreign Key [dbo].[FK__Condition__Actua__3E1D39E1]...';
=======
PRINT N'Dropping SqlForeignKeyConstraint unnamed constraint on [dbo].[Specimen]...';


GO
ALTER TABLE [dbo].[Specimen] DROP CONSTRAINT [FK__Specimen__NoteAu__12FDD1B2];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK__Participa__Actor__078C1F06]...';


GO
ALTER TABLE [dbo].[Participant] DROP CONSTRAINT [FK__Participa__Actor__078C1F06];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK_AllergyIntollerance_Entity]...';


GO
ALTER TABLE [dbo].[AllergyIntollerance] DROP CONSTRAINT [FK_AllergyIntollerance_Entity];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK__Condition__Actua__3E1D39E1]...';
>>>>>>> Stashed changes


GO
ALTER TABLE [dbo].[Condition] DROP CONSTRAINT [FK__Condition__Actua__3E1D39E1];


GO
<<<<<<< Updated upstream
PRINT N'Dropping Foreign Key [dbo].[FK__Condition__NoteA__43D61337]...';


GO
ALTER TABLE [dbo].[Condition] DROP CONSTRAINT [FK__Condition__NoteA__43D61337];


GO
PRINT N'Dropping Foreign Key [dbo].[FK__Condition__Asser__42E1EEFE]...';


GO
ALTER TABLE [dbo].[Condition] DROP CONSTRAINT [FK__Condition__Asser__42E1EEFE];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_Condition_RelatedProblems_Condition]...';


GO
ALTER TABLE [dbo].[Condition_RelatedProblems] DROP CONSTRAINT [FK_Condition_RelatedProblems_Condition];


GO
PRINT N'Dropping Foreign Key [dbo].[FK__Condition__Conte__41EDCAC5]...';


GO
ALTER TABLE [dbo].[Condition] DROP CONSTRAINT [FK__Condition__Conte__41EDCAC5];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_Condition_Evidence_Condition]...';


GO
ALTER TABLE [dbo].[Condition_Evidence] DROP CONSTRAINT [FK_Condition_Evidence_Condition];


GO
/*
The column [dbo].[Condition].[EntityId] on table [dbo].[Condition] must be added, but the column has no default value and does not allow NULL values. If the table contains data, the ALTER script will not work. To avoid this issue you must either: add a default value to the column, mark it as allowing NULL values, or enable the generation of smart-defaults as a deployment option.

The column [dbo].[Condition].[OriginalId] on table [dbo].[Condition] must be added, but the column has no default value and does not allow NULL values. If the table contains data, the ALTER script will not work. To avoid this issue you must either: add a default value to the column, mark it as allowing NULL values, or enable the generation of smart-defaults as a deployment option.

The type for column Code in table [dbo].[Condition] is currently  NVARCHAR (MAX) NULL but is being changed to  UNIQUEIDENTIFIER NULL. Data loss could occur and deployment may fail if the column contains data that is incompatible with type  UNIQUEIDENTIFIER NULL.
*/
GO
PRINT N'Starting rebuilding table [dbo].[Condition]...';


GO
BEGIN TRANSACTION;
=======
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK_ReferralRequest_RelevantHistory_Entity]...';


GO
ALTER TABLE [dbo].[ReferralRequest_RelevantHistory] DROP CONSTRAINT [FK_ReferralRequest_RelevantHistory_Entity];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK_ReferralRequest_SupportingInfo_Entity]...';


GO
ALTER TABLE [dbo].[ReferralRequest_SupportingInfo] DROP CONSTRAINT [FK_ReferralRequest_SupportingInfo_Entity];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK_Entity_EntityType]...';


GO
ALTER TABLE [dbo].[Entity] DROP CONSTRAINT [FK_Entity_EntityType];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK_Condition_Evidence_Entity]...';


GO
ALTER TABLE [dbo].[Condition_Evidence] DROP CONSTRAINT [FK_Condition_Evidence_Entity];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK_Equipment_Entity]...';


GO
ALTER TABLE [dbo].[Equipment] DROP CONSTRAINT [FK_Equipment_Entity];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK__Diagnosti__Perfo__681373AD]...';


GO
ALTER TABLE [dbo].[DiagnosticReport] DROP CONSTRAINT [FK__Diagnosti__Perfo__681373AD];
>>>>>>> Stashed changes

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

<<<<<<< Updated upstream
SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_Condition] (
    [Id]                   UNIQUEIDENTIFIER NOT NULL,
    [OriginalId]           NVARCHAR (255)   NOT NULL,
    [Identifier]           UNIQUEIDENTIFIER NULL,
    [ActualProblem]        UNIQUEIDENTIFIER NULL,
    [ProblemSignificance]  NVARCHAR (MAX)   NULL,
    [Episode]              NVARCHAR (MAX)   NULL,
    [ClinicalStatus]       NVARCHAR (MAX)   NULL,
    [VerificationStatus]   NVARCHAR (MAX)   NULL,
    [Severity]             NVARCHAR (MAX)   NULL,
    [Code]                 UNIQUEIDENTIFIER NULL,
    [BodySite]             NVARCHAR (MAX)   NULL,
    [Subject]              UNIQUEIDENTIFIER NULL,
    [Context]              UNIQUEIDENTIFIER NULL,
    [OnsetDate]            DATETIME         NULL,
    [OnsetAge]             DECIMAL (18, 2)  NULL,
    [OnsetPeriodStart]     DATETIME         NULL,
    [OnsetPeriodEnd]       DATETIME         NULL,
    [AbatementDate]        DATETIME         NULL,
    [AbatementAge]         DECIMAL (18, 2)  NULL,
    [AbatementPeriodStart] DATETIME         NULL,
    [AbatementPeriodEnd]   DATETIME         NULL,
    [Abatement]            BIT              NULL,
    [AssertedDate]         DATETIME         NOT NULL,
    [Asserter]             UNIQUEIDENTIFIER NOT NULL,
    [EvidenceCodes]        NVARCHAR (MAX)   NULL,
    [NoteText]             NVARCHAR (MAX)   NULL,
    [NoteAuthored]         DATETIME         NULL,
    [NoteAuthor]           UNIQUEIDENTIFIER NULL,
    [EntityId]             UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK__Conditio__A2B5777CD924092C1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[Condition])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_Condition] ([Id], [Identifier], [ActualProblem], [ProblemSignificance], [Episode], [ClinicalStatus], [VerificationStatus], [Severity], [Code], [BodySite], [Subject], [Context], [OnsetDate], [OnsetAge], [OnsetPeriodStart], [OnsetPeriodEnd], [AbatementDate], [AbatementAge], [AbatementPeriodStart], [AbatementPeriodEnd], [Abatement], [AssertedDate], [Asserter], [EvidenceCodes], [NoteText], [NoteAuthored], [NoteAuthor])
        SELECT   [Id],
                 [Identifier],
                 [ActualProblem],
                 [ProblemSignificance],
                 [Episode],
                 [ClinicalStatus],
                 [VerificationStatus],
                 [Severity],
                 [Code],
                 [BodySite],
                 [Subject],
                 [Context],
                 [OnsetDate],
                 [OnsetAge],
                 [OnsetPeriodStart],
                 [OnsetPeriodEnd],
                 [AbatementDate],
                 [AbatementAge],
                 [AbatementPeriodStart],
                 [AbatementPeriodEnd],
                 [Abatement],
                 [AssertedDate],
                 [Asserter],
                 [EvidenceCodes],
                 [NoteText],
                 [NoteAuthored],
                 [NoteAuthor]
        FROM     [dbo].[Condition]
        ORDER BY [Id] ASC;
    END

DROP TABLE [dbo].[Condition];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_Condition]', N'Condition';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK__Conditio__A2B5777CD924092C1]', N'PK__Conditio__A2B5777CD924092C', N'OBJECT';
=======
GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK_ReferralRequest_Entity1]...';


GO
ALTER TABLE [dbo].[ReferralRequest] DROP CONSTRAINT [FK_ReferralRequest_Entity1];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK__AllergyIn__Asser__2DE6D218]...';


GO
ALTER TABLE [dbo].[AllergyIntollerance] DROP CONSTRAINT [FK__AllergyIn__Asser__2DE6D218];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK_ReferralRequest_Entity2]...';


GO
ALTER TABLE [dbo].[ReferralRequest] DROP CONSTRAINT [FK_ReferralRequest_Entity2];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK__Condition__NoteA__43D61337]...';


GO
ALTER TABLE [dbo].[Condition] DROP CONSTRAINT [FK__Condition__NoteA__43D61337];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK_AllergyIntollerance_Entity2]...';


GO
ALTER TABLE [dbo].[AllergyIntollerance] DROP CONSTRAINT [FK_AllergyIntollerance_Entity2];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK_ReferralRequest_Entity3]...';


GO
ALTER TABLE [dbo].[ReferralRequest] DROP CONSTRAINT [FK_ReferralRequest_Entity3];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK_Immunization_Entity]...';


GO
ALTER TABLE [dbo].[Immunization] DROP CONSTRAINT [FK_Immunization_Entity];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK_Condition_RelatedClinicalConditions_Entity]...';


GO
ALTER TABLE [dbo].[Condition_RelatedClinicalConditions] DROP CONSTRAINT [FK_Condition_RelatedClinicalConditions_Entity];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK_ProcedureRequest_ConextE]...';


GO
ALTER TABLE [dbo].[ProcedureRequest] DROP CONSTRAINT [FK_ProcedureRequest_ConextE];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK_ReferralRequest_Entity]...';


GO
ALTER TABLE [dbo].[ReferralRequest] DROP CONSTRAINT [FK_ReferralRequest_Entity];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK_AllergyIntollerance_Entity1]...';


GO
ALTER TABLE [dbo].[AllergyIntollerance] DROP CONSTRAINT [FK_AllergyIntollerance_Entity1];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK__Observati__Perf]...';


GO
ALTER TABLE [dbo].[Observation] DROP CONSTRAINT [FK__Observati__Perf];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK_ReferralRequest_BasedOn_Entity]...';


GO
ALTER TABLE [dbo].[ReferralRequest_BasedOn] DROP CONSTRAINT [FK_ReferralRequest_BasedOn_Entity];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK_Condition_RelatedProblems_Entity]...';


GO
ALTER TABLE [dbo].[Condition_RelatedProblems] DROP CONSTRAINT [FK_Condition_RelatedProblems_Entity];


GO
PRINT N'Dropping SqlForeignKeyConstraint unnamed constraint on [dbo].[ActivityDefinition]...';


GO
ALTER TABLE [dbo].[ActivityDefinition] DROP CONSTRAINT [FK__ActivityD__Relat__0C85DE4D];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK__Observati__Entity]...';


GO
ALTER TABLE [dbo].[Observation] DROP CONSTRAINT [FK__Observati__Entity];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK_ReferralRequest_ReasonReference_Entity]...';


GO
ALTER TABLE [dbo].[ReferralRequest_ReasonReference] DROP CONSTRAINT [FK_ReferralRequest_ReasonReference_Entity];


GO
PRINT N'Dropping SqlForeignKeyConstraint unnamed constraint on [dbo].[DiagnosticReport]...';


GO
ALTER TABLE [dbo].[DiagnosticReport] DROP CONSTRAINT [FK__Diagnosti__Resul__1C873BEC];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK__Immunizat__React__74AE54BC]...';


GO
ALTER TABLE [dbo].[Immunization] DROP CONSTRAINT [FK__Immunizat__React__74AE54BC];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK__Observati__Observation]...';


GO
ALTER TABLE [dbo].[Observation] DROP CONSTRAINT [FK__Observati__Observation];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK__Observati__Subje__40F9A68C]...';


GO
ALTER TABLE [dbo].[Observation] DROP CONSTRAINT [FK__Observati__Subje__40F9A68C];


GO
PRINT N'Dropping SqlForeignKeyConstraint unnamed constraint on [dbo].[Observation]...';


GO
ALTER TABLE [dbo].[Observation] DROP CONSTRAINT [FK__Observati__Perfo__1B9317B3];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK__Observati__Device]...';


GO
ALTER TABLE [dbo].[Observation] DROP CONSTRAINT [FK__Observati__Device];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK__Observati__Conte__534D60F1]...';


GO
ALTER TABLE [dbo].[Observation] DROP CONSTRAINT [FK__Observati__Conte__534D60F1];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK__Immunizat__Subje__6FE99F9F]...';


GO
ALTER TABLE [dbo].[Immunization] DROP CONSTRAINT [FK__Immunizat__Subje__6FE99F9F];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK__Specimen__Subjec__6FB49575]...';


GO
ALTER TABLE [dbo].[Specimen] DROP CONSTRAINT [FK__Specimen__Subjec__6FB49575];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK_ReferralRequest_Patient]...';


GO
ALTER TABLE [dbo].[ReferralRequest] DROP CONSTRAINT [FK_ReferralRequest_Patient];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK__Medicatio__Patie__3E1D39E1]...';


GO
ALTER TABLE [dbo].[MedicationStatement] DROP CONSTRAINT [FK__Medicatio__Patie__3E1D39E1];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK_Compositio_Patient]...';


GO
ALTER TABLE [dbo].[Composition] DROP CONSTRAINT [FK_Compositio_Patient];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK__Encounter__Patie__412EB0B6]...';


GO
ALTER TABLE [dbo].[Encounter] DROP CONSTRAINT [FK__Encounter__Patie__412EB0B6];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK_Patient_Organization]...';


GO
ALTER TABLE [dbo].[Patient] DROP CONSTRAINT [FK_Patient_Organization];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK_Patient_Address_Patient]...';


GO
ALTER TABLE [dbo].[Patient_Address] DROP CONSTRAINT [FK_Patient_Address_Patient];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK_Patient_Patient]...';


GO
ALTER TABLE [dbo].[Patient] DROP CONSTRAINT [FK_Patient_Patient];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK_Patient_Links_Patient]...';


GO
ALTER TABLE [dbo].[Patient_Links] DROP CONSTRAINT [FK_Patient_Links_Patient];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK_ProcedureRequest_Subject]...';


GO
ALTER TABLE [dbo].[ProcedureRequest] DROP CONSTRAINT [FK_ProcedureRequest_Subject];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK__Condition__Subje__40F9A68C]...';


GO
ALTER TABLE [dbo].[Condition] DROP CONSTRAINT [FK__Condition__Subje__40F9A68C];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK_Patient_Practicioner]...';


GO
ALTER TABLE [dbo].[Patient] DROP CONSTRAINT [FK_Patient_Practicioner];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK_Patient_Organization1]...';


GO
ALTER TABLE [dbo].[Patient] DROP CONSTRAINT [FK_Patient_Organization1];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK_Patient_Links_Patient1]...';


GO
ALTER TABLE [dbo].[Patient_Links] DROP CONSTRAINT [FK_Patient_Links_Patient1];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK__AllergyIn__Subje__2CF2ADDF]...';


GO
ALTER TABLE [dbo].[AllergyIntollerance] DROP CONSTRAINT [FK__AllergyIn__Subje__2CF2ADDF];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK__Medicatio__Patie__3A4CA8FD]...';


GO
ALTER TABLE [dbo].[MedicationRequest] DROP CONSTRAINT [FK__Medicatio__Patie__3A4CA8FD];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK_Patient_Contacts_Patient]...';


GO
ALTER TABLE [dbo].[Patient_Contacts] DROP CONSTRAINT [FK_Patient_Contacts_Patient];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK__Diagnosti__Subje__1EA48E88]...';


GO
ALTER TABLE [dbo].[DiagnosticReport] DROP CONSTRAINT [FK__Diagnosti__Subje__1EA48E88];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK__AllergyIn__NoteA__31B762FC]...';


GO
ALTER TABLE [dbo].[AllergyIntollerance] DROP CONSTRAINT [FK__AllergyIn__NoteA__31B762FC];


GO
PRINT N'Altering SqlTable [dbo].[Coding]...';


GO
ALTER TABLE [dbo].[Coding] ALTER COLUMN [SnomedCode] BIGINT NULL;


GO
PRINT N'Starting rebuilding table [dbo].[Entity]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_Entity] (
    [Id]         UNIQUEIDENTIFIER NOT NULL,
    [OriginalId] NVARCHAR (250)   NULL,
    [EntityType] INT              NOT NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_Entity1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[Entity])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_Entity] ([Id], [EntityType])
        SELECT   [Id],
                 [EntityType]
        FROM     [dbo].[Entity]
        ORDER BY [Id] ASC;
    END

DROP TABLE [dbo].[Entity];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_Entity]', N'Entity';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_Entity1]', N'PK_Entity', N'OBJECT';
>>>>>>> Stashed changes

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
<<<<<<< Updated upstream
PRINT N'Creating Foreign Key [dbo].[FK__Condition__Subje__40F9A68C]...';
=======
/*
The column [dbo].[Observation].[ReferenceRangeAge] is being dropped, data loss could occur.

The type for column Code in table [dbo].[Observation] is currently  NVARCHAR (MAX) NULL but is being changed to  UNIQUEIDENTIFIER NULL. Data loss could occur and deployment may fail if the column contains data that is incompatible with type  UNIQUEIDENTIFIER NULL.

The type for column ReferenceRangeHigh in table [dbo].[Observation] is currently  INT NULL but is being changed to  DECIMAL (18, 2) NULL. Data loss could occur and deployment may fail if the column contains data that is incompatible with type  DECIMAL (18, 2) NULL.

The type for column ReferenceRangeLow in table [dbo].[Observation] is currently  INT NULL but is being changed to  DECIMAL (18, 2) NULL. Data loss could occur and deployment may fail if the column contains data that is incompatible with type  DECIMAL (18, 2) NULL.
*/
GO
PRINT N'Starting rebuilding table [dbo].[Observation]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_Observation] (
    [Id]                      UNIQUEIDENTIFIER NOT NULL,
    [OriginalId]              NVARCHAR (200)   NULL,
    [Status]                  NVARCHAR (MAX)   NULL,
    [Category]                NVARCHAR (MAX)   NULL,
    [Code]                    UNIQUEIDENTIFIER NULL,
    [BasedOn]                 UNIQUEIDENTIFIER NULL,
    [SubjectId]               UNIQUEIDENTIFIER NULL,
    [ContextId]               UNIQUEIDENTIFIER NULL,
    [EffectiveDate]           DATETIME         NULL,
    [EffectiveDateFrom]       DATETIME         NULL,
    [EffectiveDateTo]         DATETIME         NULL,
    [Issued]                  DATETIME         NULL,
    [PerformerId]             UNIQUEIDENTIFIER NULL,
    [Interpretation]          NVARCHAR (MAX)   NULL,
    [DataAbsentReason]        NVARCHAR (MAX)   NULL,
    [Comment]                 NVARCHAR (MAX)   NULL,
    [BodySite]                NVARCHAR (MAX)   NULL,
    [Method]                  NVARCHAR (MAX)   NULL,
    [Device]                  UNIQUEIDENTIFIER NULL,
    [ReferenceText]           NVARCHAR (200)   NULL,
    [ReferenceRangeLow]       DECIMAL (18, 2)  NULL,
    [ReferenceRangeLowUnit]   NVARCHAR (200)   NULL,
    [ReferenceRangeHigh]      DECIMAL (18, 2)  NULL,
    [ReferenceRangeHighUnit]  NVARCHAR (200)   NULL,
    [ReferenceRangeType]      NVARCHAR (MAX)   NULL,
    [ReferenceRangeAppliesTo] NVARCHAR (MAX)   NULL,
    [ReferenceRangeAgeHigh]   DECIMAL (18, 2)  NULL,
    [ReferenceRangeAgeLow]    DECIMAL (18, 2)  NULL,
    [RelatedTo]               UNIQUEIDENTIFIER NULL,
    [Entityid]                UNIQUEIDENTIFIER NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[Observation])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_Observation] ([Id], [OriginalId], [Status], [Category], [Code], [SubjectId], [ContextId], [EffectiveDate], [EffectiveDateFrom], [EffectiveDateTo], [Issued], [PerformerId], [Interpretation], [DataAbsentReason], [Comment], [BodySite], [Method], [Device], [ReferenceRangeLow], [ReferenceRangeHigh], [ReferenceRangeType], [ReferenceRangeAppliesTo], [RelatedTo], [Entityid])
        SELECT   [Id],
                 [OriginalId],
                 [Status],
                 [Category],
                 [Code],
                 [SubjectId],
                 [ContextId],
                 [EffectiveDate],
                 [EffectiveDateFrom],
                 [EffectiveDateTo],
                 [Issued],
                 [PerformerId],
                 [Interpretation],
                 [DataAbsentReason],
                 [Comment],
                 [BodySite],
                 [Method],
                 [Device],
                 [ReferenceRangeLow],
                 [ReferenceRangeHigh],
                 [ReferenceRangeType],
                 [ReferenceRangeAppliesTo],
                 [RelatedTo],
                 [Entityid]
        FROM     [dbo].[Observation]
        ORDER BY [Id] ASC;
    END

DROP TABLE [dbo].[Observation];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_Observation]', N'Observation';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
/*
The column [dbo].[Patient].[Sex] is being dropped, data loss could occur.
*/
GO
PRINT N'Starting rebuilding table [dbo].[Patient]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_Patient] (
    [Id]                       UNIQUEIDENTIFIER NOT NULL,
    [OriginalId]               NVARCHAR (255)   NOT NULL,
    [ManagingOrganization]     UNIQUEIDENTIFIER NOT NULL,
    [Practicioner]             UNIQUEIDENTIFIER NOT NULL,
    [HomeAddress]              UNIQUEIDENTIFIER NULL,
    [Gender]                   NVARCHAR (255)   NULL,
    [DateOfBirthUTC]           DATETIME         NOT NULL,
    [DateOfDeathUTC]           DATETIME         NULL,
    [Title]                    NVARCHAR (255)   NULL,
    [GivenName]                NVARCHAR (255)   NOT NULL,
    [MiddleNames]              NVARCHAR (MAX)   NULL,
    [Surname]                  NVARCHAR (255)   NOT NULL,
    [DateOfRegistrationUTC]    DATETIME         NULL,
    [NhsNumber]                NVARCHAR (255)   NULL,
    [PatientNumber]            NVARCHAR (255)   NULL,
    [PatientTypeDescription]   NVARCHAR (255)   NULL,
    [DummyType]                NVARCHAR (255)   NULL,
    [ResidentialInstituteCode] NVARCHAR (255)   NULL,
    [NHSNumberStatus]          NVARCHAR (255)   NULL,
    [CarerName]                NVARCHAR (255)   NULL,
    [CarerRelation]            NVARCHAR (255)   NULL,
    [PersonGuid]               NVARCHAR (255)   NULL,
    [DateOfDeactivation]       DATETIME         NULL,
    [Deleted]                  BIT              NULL,
    [Active]                   BIT              NULL,
    [SpineSensitive]           BIT              NULL,
    [IsConfidential]           BIT              NULL,
    [EmailAddress]             NVARCHAR (255)   NULL,
    [HomePhone]                NVARCHAR (20)    NULL,
    [MobilePhone]              NVARCHAR (20)    NULL,
    [ProcessingId]             NVARCHAR (255)   NULL,
    [Ethnicity]                NVARCHAR (255)   NULL,
    [Religion]                 NVARCHAR (255)   NULL,
    [NominatedPharmacy]        UNIQUEIDENTIFIER NULL,
    [EntityId]                 UNIQUEIDENTIFIER NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK__Patient__DBA60F19AE6332BC1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[Patient])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_Patient] ([Id], [OriginalId], [ManagingOrganization], [Practicioner], [HomeAddress], [DateOfBirthUTC], [DateOfDeathUTC], [Title], [GivenName], [MiddleNames], [Surname], [DateOfRegistrationUTC], [NhsNumber], [PatientNumber], [PatientTypeDescription], [DummyType], [ResidentialInstituteCode], [NHSNumberStatus], [CarerName], [CarerRelation], [PersonGuid], [DateOfDeactivation], [Deleted], [Active], [SpineSensitive], [IsConfidential], [EmailAddress], [HomePhone], [MobilePhone], [ProcessingId], [Ethnicity], [Religion], [NominatedPharmacy], [EntityId])
        SELECT   [Id],
                 [OriginalId],
                 [ManagingOrganization],
                 [Practicioner],
                 [HomeAddress],
                 [DateOfBirthUTC],
                 [DateOfDeathUTC],
                 [Title],
                 [GivenName],
                 [MiddleNames],
                 [Surname],
                 [DateOfRegistrationUTC],
                 [NhsNumber],
                 [PatientNumber],
                 [PatientTypeDescription],
                 [DummyType],
                 [ResidentialInstituteCode],
                 [NHSNumberStatus],
                 [CarerName],
                 [CarerRelation],
                 [PersonGuid],
                 [DateOfDeactivation],
                 [Deleted],
                 [Active],
                 [SpineSensitive],
                 [IsConfidential],
                 [EmailAddress],
                 [HomePhone],
                 [MobilePhone],
                 [ProcessingId],
                 [Ethnicity],
                 [Religion],
                 [NominatedPharmacy],
                 [EntityId]
        FROM     [dbo].[Patient]
        ORDER BY [Id] ASC;
    END

DROP TABLE [dbo].[Patient];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_Patient]', N'Patient';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK__Patient__DBA60F19AE6332BC1]', N'PK__Patient__DBA60F19AE6332BC', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Altering SqlTable [dbo].[Practicioner]...';


GO
ALTER TABLE [dbo].[Practicioner] ALTER COLUMN [GivenName] NVARCHAR (100) NULL;


GO
PRINT N'Creating SqlTable [dbo].[Refset]...';


GO
CREATE TABLE [dbo].[Refset] (
    [Output_ID]               NVARCHAR (50)  NOT NULL,
    [Cluster_ID]              NVARCHAR (50)  NOT NULL,
    [Cluster_Description]     NVARCHAR (255) NOT NULL,
    [SNOMED_code]             BIGINT         NULL,
    [SNOMED_code_description] NVARCHAR (300) NOT NULL,
    [PCD_Refset_ID]           BIGINT         NOT NULL
);


GO
PRINT N'Creating SqlIndex [dbo].[Refset].[ClusteredIndex-20240304-122812]...';


GO
CREATE CLUSTERED INDEX [ClusteredIndex-20240304-122812]
    ON [dbo].[Refset]([SNOMED_code] ASC, [PCD_Refset_ID] ASC)
    ON [PRIMARY];


GO
PRINT N'Creating SqlForeignKeyConstraint unnamed constraint on [dbo].[Specimen]...';
>>>>>>> Stashed changes


GO
WAITFOR DELAY '00:00.010';

<<<<<<< Updated upstream
ALTER TABLE [dbo].[Condition] WITH NOCHECK
    ADD CONSTRAINT [FK__Condition__Subje__40F9A68C] FOREIGN KEY ([Subject]) REFERENCES [dbo].[Patient] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Condition__Ident__3D2915A8]...';
=======
ALTER TABLE [dbo].[Specimen] WITH NOCHECK
    ADD FOREIGN KEY ([NoteAuthorId]) REFERENCES [dbo].[Entity] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK__Participa__Actor__078C1F06]...';
>>>>>>> Stashed changes


GO
WAITFOR DELAY '00:00.010';

<<<<<<< Updated upstream
ALTER TABLE [dbo].[Condition] WITH NOCHECK
    ADD CONSTRAINT [FK__Condition__Ident__3D2915A8] FOREIGN KEY ([Identifier]) REFERENCES [dbo].[Identifier] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Condition_RelatedClinicalConditions_Condition]...';
=======
ALTER TABLE [dbo].[Participant] WITH NOCHECK
    ADD CONSTRAINT [FK__Participa__Actor__078C1F06] FOREIGN KEY ([Actor]) REFERENCES [dbo].[Entity] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK_AllergyIntollerance_Entity]...';
>>>>>>> Stashed changes


GO
WAITFOR DELAY '00:00.010';

<<<<<<< Updated upstream
ALTER TABLE [dbo].[Condition_RelatedClinicalConditions] WITH NOCHECK
    ADD CONSTRAINT [FK_Condition_RelatedClinicalConditions_Condition] FOREIGN KEY ([ConditionId]) REFERENCES [dbo].[Condition] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Condition__Actua__3E1D39E1]...';
=======
ALTER TABLE [dbo].[AllergyIntollerance] WITH NOCHECK
    ADD CONSTRAINT [FK_AllergyIntollerance_Entity] FOREIGN KEY ([Recorder]) REFERENCES [dbo].[Entity] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK__Condition__Actua__3E1D39E1]...';
>>>>>>> Stashed changes


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[Condition] WITH NOCHECK
    ADD CONSTRAINT [FK__Condition__Actua__3E1D39E1] FOREIGN KEY ([ActualProblem]) REFERENCES [dbo].[Entity] ([Id]);


GO
<<<<<<< Updated upstream
PRINT N'Creating Foreign Key [dbo].[FK__Condition__NoteA__43D61337]...';
=======
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK_ReferralRequest_RelevantHistory_Entity]...';
>>>>>>> Stashed changes


GO
WAITFOR DELAY '00:00.010';

<<<<<<< Updated upstream
ALTER TABLE [dbo].[Condition] WITH NOCHECK
    ADD CONSTRAINT [FK__Condition__NoteA__43D61337] FOREIGN KEY ([NoteAuthor]) REFERENCES [dbo].[Entity] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Condition__Asser__42E1EEFE]...';
=======
ALTER TABLE [dbo].[ReferralRequest_RelevantHistory] WITH NOCHECK
    ADD CONSTRAINT [FK_ReferralRequest_RelevantHistory_Entity] FOREIGN KEY ([Entity]) REFERENCES [dbo].[Entity] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK_ReferralRequest_SupportingInfo_Entity]...';
>>>>>>> Stashed changes


GO
WAITFOR DELAY '00:00.010';

<<<<<<< Updated upstream
ALTER TABLE [dbo].[Condition] WITH NOCHECK
    ADD CONSTRAINT [FK__Condition__Asser__42E1EEFE] FOREIGN KEY ([Asserter]) REFERENCES [dbo].[Practicioner] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Condition_RelatedProblems_Condition]...';
=======
ALTER TABLE [dbo].[ReferralRequest_SupportingInfo] WITH NOCHECK
    ADD CONSTRAINT [FK_ReferralRequest_SupportingInfo_Entity] FOREIGN KEY ([Entity]) REFERENCES [dbo].[Entity] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK_Entity_EntityType]...';
>>>>>>> Stashed changes


GO
WAITFOR DELAY '00:00.010';

<<<<<<< Updated upstream
ALTER TABLE [dbo].[Condition_RelatedProblems] WITH NOCHECK
    ADD CONSTRAINT [FK_Condition_RelatedProblems_Condition] FOREIGN KEY ([ConditionId]) REFERENCES [dbo].[Condition] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Condition__Conte__41EDCAC5]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[Condition] WITH NOCHECK
    ADD CONSTRAINT [FK__Condition__Conte__41EDCAC5] FOREIGN KEY ([Context]) REFERENCES [dbo].[Encounter] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Condition_Evidence_Condition]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[Condition_Evidence] WITH NOCHECK
    ADD CONSTRAINT [FK_Condition_Evidence_Condition] FOREIGN KEY ([ConditionId]) REFERENCES [dbo].[Condition] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Condition__Code]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[Condition] WITH NOCHECK
    ADD CONSTRAINT [FK__Condition__Code] FOREIGN KEY ([Code]) REFERENCES [dbo].[Coding] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Condition__Entity]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[Condition] WITH NOCHECK
    ADD CONSTRAINT [FK__Condition__Entity] FOREIGN KEY ([EntityId]) REFERENCES [dbo].[Entity] ([Id]);
=======
ALTER TABLE [dbo].[Entity] WITH NOCHECK
    ADD CONSTRAINT [FK_Entity_EntityType] FOREIGN KEY ([EntityType]) REFERENCES [dbo].[EntityType] ([EntityType]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK_Condition_Evidence_Entity]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[Condition_Evidence] WITH NOCHECK
    ADD CONSTRAINT [FK_Condition_Evidence_Entity] FOREIGN KEY ([EntityId]) REFERENCES [dbo].[Entity] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK_Equipment_Entity]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[Equipment] WITH NOCHECK
    ADD CONSTRAINT [FK_Equipment_Entity] FOREIGN KEY ([EntityId]) REFERENCES [dbo].[Entity] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK__Diagnosti__Perfo__681373AD]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[DiagnosticReport] WITH NOCHECK
    ADD CONSTRAINT [FK__Diagnosti__Perfo__681373AD] FOREIGN KEY ([Performer]) REFERENCES [dbo].[Entity] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK_ReferralRequest_Entity1]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[ReferralRequest] WITH NOCHECK
    ADD CONSTRAINT [FK_ReferralRequest_Entity1] FOREIGN KEY ([Requester]) REFERENCES [dbo].[Entity] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK__AllergyIn__Asser__2DE6D218]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[AllergyIntollerance] WITH NOCHECK
    ADD CONSTRAINT [FK__AllergyIn__Asser__2DE6D218] FOREIGN KEY ([Asserter]) REFERENCES [dbo].[Entity] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK_ReferralRequest_Entity2]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[ReferralRequest] WITH NOCHECK
    ADD CONSTRAINT [FK_ReferralRequest_Entity2] FOREIGN KEY ([Recipient]) REFERENCES [dbo].[Entity] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK__Condition__NoteA__43D61337]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[Condition] WITH NOCHECK
    ADD CONSTRAINT [FK__Condition__NoteA__43D61337] FOREIGN KEY ([NoteAuthor]) REFERENCES [dbo].[Entity] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK_AllergyIntollerance_Entity2]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[AllergyIntollerance] WITH NOCHECK
    ADD CONSTRAINT [FK_AllergyIntollerance_Entity2] FOREIGN KEY ([Asserter]) REFERENCES [dbo].[Entity] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK_ReferralRequest_Entity3]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[ReferralRequest] WITH NOCHECK
    ADD CONSTRAINT [FK_ReferralRequest_Entity3] FOREIGN KEY ([NoteAuthor]) REFERENCES [dbo].[Entity] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK_Immunization_Entity]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[Immunization] WITH NOCHECK
    ADD CONSTRAINT [FK_Immunization_Entity] FOREIGN KEY ([EntityId]) REFERENCES [dbo].[Entity] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK_Condition_RelatedClinicalConditions_Entity]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[Condition_RelatedClinicalConditions] WITH NOCHECK
    ADD CONSTRAINT [FK_Condition_RelatedClinicalConditions_Entity] FOREIGN KEY ([EntityId]) REFERENCES [dbo].[Entity] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK_ProcedureRequest_ConextE]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[ProcedureRequest] WITH NOCHECK
    ADD CONSTRAINT [FK_ProcedureRequest_ConextE] FOREIGN KEY ([Conext]) REFERENCES [dbo].[Entity] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK_ReferralRequest_Entity]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[ReferralRequest] WITH NOCHECK
    ADD CONSTRAINT [FK_ReferralRequest_Entity] FOREIGN KEY ([Context]) REFERENCES [dbo].[Entity] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK_AllergyIntollerance_Entity1]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[AllergyIntollerance] WITH NOCHECK
    ADD CONSTRAINT [FK_AllergyIntollerance_Entity1] FOREIGN KEY ([NoteAuthor]) REFERENCES [dbo].[Entity] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK__Observati__Perf]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[Observation] WITH NOCHECK
    ADD CONSTRAINT [FK__Observati__Perf] FOREIGN KEY ([PerformerId]) REFERENCES [dbo].[Entity] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK_ReferralRequest_BasedOn_Entity]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[ReferralRequest_BasedOn] WITH NOCHECK
    ADD CONSTRAINT [FK_ReferralRequest_BasedOn_Entity] FOREIGN KEY ([EntityId]) REFERENCES [dbo].[Entity] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK_Condition_RelatedProblems_Entity]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[Condition_RelatedProblems] WITH NOCHECK
    ADD CONSTRAINT [FK_Condition_RelatedProblems_Entity] FOREIGN KEY ([EntityId]) REFERENCES [dbo].[Entity] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint unnamed constraint on [dbo].[ActivityDefinition]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[ActivityDefinition] WITH NOCHECK
    ADD FOREIGN KEY ([RelatedArtifactId]) REFERENCES [dbo].[Entity] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK__Observati__Entity]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[Observation] WITH NOCHECK
    ADD CONSTRAINT [FK__Observati__Entity] FOREIGN KEY ([Entityid]) REFERENCES [dbo].[Entity] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK_ReferralRequest_ReasonReference_Entity]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[ReferralRequest_ReasonReference] WITH NOCHECK
    ADD CONSTRAINT [FK_ReferralRequest_ReasonReference_Entity] FOREIGN KEY ([Entity]) REFERENCES [dbo].[Entity] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint unnamed constraint on [dbo].[DiagnosticReport]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[DiagnosticReport] WITH NOCHECK
    ADD FOREIGN KEY ([Result]) REFERENCES [dbo].[Observation] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK__Immunizat__React__74AE54BC]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[Immunization] WITH NOCHECK
    ADD CONSTRAINT [FK__Immunizat__React__74AE54BC] FOREIGN KEY ([ReactionDetailId]) REFERENCES [dbo].[Observation] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK__Observati__Observation]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[Observation] WITH NOCHECK
    ADD CONSTRAINT [FK__Observati__Observation] FOREIGN KEY ([RelatedTo]) REFERENCES [dbo].[Observation] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK__Observati__Subje__40F9A68C]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[Observation] WITH NOCHECK
    ADD CONSTRAINT [FK__Observati__Subje__40F9A68C] FOREIGN KEY ([SubjectId]) REFERENCES [dbo].[Patient] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint unnamed constraint on [dbo].[Observation]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[Observation] WITH NOCHECK
    ADD FOREIGN KEY ([PerformerId]) REFERENCES [dbo].[Practicioner] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK__Observati__Device]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[Observation] WITH NOCHECK
    ADD CONSTRAINT [FK__Observati__Device] FOREIGN KEY ([Device]) REFERENCES [dbo].[Device] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK__Observati__Conte__534D60F1]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[Observation] WITH NOCHECK
    ADD CONSTRAINT [FK__Observati__Conte__534D60F1] FOREIGN KEY ([ContextId]) REFERENCES [dbo].[Encounter] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK__Observati__basedOn]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[Observation] WITH NOCHECK
    ADD CONSTRAINT [FK__Observati__basedOn] FOREIGN KEY ([BasedOn]) REFERENCES [dbo].[Entity] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK__Observati__Coding]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[Observation] WITH NOCHECK
    ADD CONSTRAINT [FK__Observati__Coding] FOREIGN KEY ([Code]) REFERENCES [dbo].[Coding] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK__Immunizat__Subje__6FE99F9F]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[Immunization] WITH NOCHECK
    ADD CONSTRAINT [FK__Immunizat__Subje__6FE99F9F] FOREIGN KEY ([SubjectId]) REFERENCES [dbo].[Patient] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK__Specimen__Subjec__6FB49575]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[Specimen] WITH NOCHECK
    ADD CONSTRAINT [FK__Specimen__Subjec__6FB49575] FOREIGN KEY ([SubjectId]) REFERENCES [dbo].[Patient] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK_ReferralRequest_Patient]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[ReferralRequest] WITH NOCHECK
    ADD CONSTRAINT [FK_ReferralRequest_Patient] FOREIGN KEY ([Subject]) REFERENCES [dbo].[Patient] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK__Medicatio__Patie__3E1D39E1]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[MedicationStatement] WITH NOCHECK
    ADD CONSTRAINT [FK__Medicatio__Patie__3E1D39E1] FOREIGN KEY ([Subject]) REFERENCES [dbo].[Patient] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK_Compositio_Patient]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[Composition] WITH NOCHECK
    ADD CONSTRAINT [FK_Compositio_Patient] FOREIGN KEY ([Subject]) REFERENCES [dbo].[Patient] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK__Encounter__Patie__412EB0B6]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[Encounter] WITH NOCHECK
    ADD CONSTRAINT [FK__Encounter__Patie__412EB0B6] FOREIGN KEY ([PatientGuid]) REFERENCES [dbo].[Patient] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK_Patient_Organization]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[Patient] WITH NOCHECK
    ADD CONSTRAINT [FK_Patient_Organization] FOREIGN KEY ([ManagingOrganization]) REFERENCES [dbo].[Organization] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK_Patient_Address_Patient]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[Patient_Address] WITH NOCHECK
    ADD CONSTRAINT [FK_Patient_Address_Patient] FOREIGN KEY ([PatientId]) REFERENCES [dbo].[Patient] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK_Patient_Patient]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[Patient] WITH NOCHECK
    ADD CONSTRAINT [FK_Patient_Patient] FOREIGN KEY ([Id]) REFERENCES [dbo].[Patient] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK_Patient_Links_Patient]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[Patient_Links] WITH NOCHECK
    ADD CONSTRAINT [FK_Patient_Links_Patient] FOREIGN KEY ([PatientId]) REFERENCES [dbo].[Patient] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK_ProcedureRequest_Subject]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[ProcedureRequest] WITH NOCHECK
    ADD CONSTRAINT [FK_ProcedureRequest_Subject] FOREIGN KEY ([Subject]) REFERENCES [dbo].[Patient] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK__Condition__Subje__40F9A68C]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[Condition] WITH NOCHECK
    ADD CONSTRAINT [FK__Condition__Subje__40F9A68C] FOREIGN KEY ([Subject]) REFERENCES [dbo].[Patient] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK_Patient_Practicioner]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[Patient] WITH NOCHECK
    ADD CONSTRAINT [FK_Patient_Practicioner] FOREIGN KEY ([Practicioner]) REFERENCES [dbo].[Practicioner] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK_Patient_Organization1]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[Patient] WITH NOCHECK
    ADD CONSTRAINT [FK_Patient_Organization1] FOREIGN KEY ([NominatedPharmacy]) REFERENCES [dbo].[Organization] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK_Patient_Links_Patient1]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[Patient_Links] WITH NOCHECK
    ADD CONSTRAINT [FK_Patient_Links_Patient1] FOREIGN KEY ([LinkedPatient]) REFERENCES [dbo].[Patient] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK__AllergyIn__Subje__2CF2ADDF]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[AllergyIntollerance] WITH NOCHECK
    ADD CONSTRAINT [FK__AllergyIn__Subje__2CF2ADDF] FOREIGN KEY ([Subject]) REFERENCES [dbo].[Patient] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK__Medicatio__Patie__3A4CA8FD]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[MedicationRequest] WITH NOCHECK
    ADD CONSTRAINT [FK__Medicatio__Patie__3A4CA8FD] FOREIGN KEY ([Subject]) REFERENCES [dbo].[Patient] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK_Patient_Contacts_Patient]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[Patient_Contacts] WITH NOCHECK
    ADD CONSTRAINT [FK_Patient_Contacts_Patient] FOREIGN KEY ([PatientId]) REFERENCES [dbo].[Patient] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK__Diagnosti__Subje__1EA48E88]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[DiagnosticReport] WITH NOCHECK
    ADD CONSTRAINT [FK__Diagnosti__Subje__1EA48E88] FOREIGN KEY ([Subject]) REFERENCES [dbo].[Patient] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK__AllergyIn__NoteA__31B762FC]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[AllergyIntollerance] WITH NOCHECK
    ADD CONSTRAINT [FK__AllergyIn__NoteA__31B762FC] FOREIGN KEY ([NoteAuthor]) REFERENCES [dbo].[Patient] ([Id]);
>>>>>>> Stashed changes


GO
BEGIN
	-- Disable constraints for all tables:
	EXEC sp_msforeachtable 'ALTER TABLE ? NOCHECK CONSTRAINT all'
    DELETE FROM [dbo].[EntityType]
	INSERT [dbo].[EntityType] ([EntityType], [EntityName]) VALUES (1,N'Organization')
	INSERT [dbo].[EntityType] ([EntityType], [EntityName]) VALUES (2,N'Location')
	INSERT [dbo].[EntityType] ([EntityType], [EntityName]) VALUES (3,N'Patient')
	INSERT [dbo].[EntityType] ([EntityType], [EntityName]) VALUES (4,N'Practitioner')
	INSERT [dbo].[EntityType] ([EntityType], [EntityName]) VALUES (5,N'Observation')
	INSERT [dbo].[EntityType] ([EntityType], [EntityName]) VALUES (6,N'Condition')
    INSERT [dbo].[EntityType] ([EntityType], [EntityName]) VALUES (7,N'DiaryEntry')
    INSERT [dbo].[EntityType] ([EntityType], [EntityName]) VALUES (8,N'ProcedureRequest')
	-- Re-enable constraints for all tables:
	EXEC sp_msforeachtable 'ALTER TABLE ? WITH CHECK CHECK CONSTRAINT all';	
END 
GO

GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
<<<<<<< Updated upstream
ALTER TABLE [dbo].[Condition] WITH CHECK CHECK CONSTRAINT [FK__Condition__Subje__40F9A68C];

ALTER TABLE [dbo].[Condition] WITH CHECK CHECK CONSTRAINT [FK__Condition__Ident__3D2915A8];

ALTER TABLE [dbo].[Condition_RelatedClinicalConditions] WITH CHECK CHECK CONSTRAINT [FK_Condition_RelatedClinicalConditions_Condition];

ALTER TABLE [dbo].[Condition] WITH CHECK CHECK CONSTRAINT [FK__Condition__Actua__3E1D39E1];

ALTER TABLE [dbo].[Condition] WITH CHECK CHECK CONSTRAINT [FK__Condition__NoteA__43D61337];

ALTER TABLE [dbo].[Condition] WITH CHECK CHECK CONSTRAINT [FK__Condition__Asser__42E1EEFE];

ALTER TABLE [dbo].[Condition_RelatedProblems] WITH CHECK CHECK CONSTRAINT [FK_Condition_RelatedProblems_Condition];

ALTER TABLE [dbo].[Condition] WITH CHECK CHECK CONSTRAINT [FK__Condition__Conte__41EDCAC5];

ALTER TABLE [dbo].[Condition_Evidence] WITH CHECK CHECK CONSTRAINT [FK_Condition_Evidence_Condition];

ALTER TABLE [dbo].[Condition] WITH CHECK CHECK CONSTRAINT [FK__Condition__Code];

ALTER TABLE [dbo].[Condition] WITH CHECK CHECK CONSTRAINT [FK__Condition__Entity];
=======
ALTER TABLE [dbo].[Participant] WITH CHECK CHECK CONSTRAINT [FK__Participa__Actor__078C1F06];

ALTER TABLE [dbo].[AllergyIntollerance] WITH CHECK CHECK CONSTRAINT [FK_AllergyIntollerance_Entity];

ALTER TABLE [dbo].[Condition] WITH CHECK CHECK CONSTRAINT [FK__Condition__Actua__3E1D39E1];

ALTER TABLE [dbo].[ReferralRequest_RelevantHistory] WITH CHECK CHECK CONSTRAINT [FK_ReferralRequest_RelevantHistory_Entity];

ALTER TABLE [dbo].[ReferralRequest_SupportingInfo] WITH CHECK CHECK CONSTRAINT [FK_ReferralRequest_SupportingInfo_Entity];

ALTER TABLE [dbo].[Entity] WITH CHECK CHECK CONSTRAINT [FK_Entity_EntityType];

ALTER TABLE [dbo].[Condition_Evidence] WITH CHECK CHECK CONSTRAINT [FK_Condition_Evidence_Entity];

ALTER TABLE [dbo].[Equipment] WITH CHECK CHECK CONSTRAINT [FK_Equipment_Entity];

ALTER TABLE [dbo].[ReferralRequest] WITH CHECK CHECK CONSTRAINT [FK_ReferralRequest_Entity1];

ALTER TABLE [dbo].[AllergyIntollerance] WITH CHECK CHECK CONSTRAINT [FK__AllergyIn__Asser__2DE6D218];

ALTER TABLE [dbo].[ReferralRequest] WITH CHECK CHECK CONSTRAINT [FK_ReferralRequest_Entity2];

ALTER TABLE [dbo].[Condition] WITH CHECK CHECK CONSTRAINT [FK__Condition__NoteA__43D61337];

ALTER TABLE [dbo].[AllergyIntollerance] WITH CHECK CHECK CONSTRAINT [FK_AllergyIntollerance_Entity2];

ALTER TABLE [dbo].[ReferralRequest] WITH CHECK CHECK CONSTRAINT [FK_ReferralRequest_Entity3];

ALTER TABLE [dbo].[Immunization] WITH CHECK CHECK CONSTRAINT [FK_Immunization_Entity];

ALTER TABLE [dbo].[Condition_RelatedClinicalConditions] WITH CHECK CHECK CONSTRAINT [FK_Condition_RelatedClinicalConditions_Entity];

ALTER TABLE [dbo].[ProcedureRequest] WITH CHECK CHECK CONSTRAINT [FK_ProcedureRequest_ConextE];

ALTER TABLE [dbo].[ReferralRequest] WITH CHECK CHECK CONSTRAINT [FK_ReferralRequest_Entity];

ALTER TABLE [dbo].[AllergyIntollerance] WITH CHECK CHECK CONSTRAINT [FK_AllergyIntollerance_Entity1];

ALTER TABLE [dbo].[ReferralRequest_BasedOn] WITH CHECK CHECK CONSTRAINT [FK_ReferralRequest_BasedOn_Entity];

ALTER TABLE [dbo].[Condition_RelatedProblems] WITH CHECK CHECK CONSTRAINT [FK_Condition_RelatedProblems_Entity];

ALTER TABLE [dbo].[ReferralRequest_ReasonReference] WITH CHECK CHECK CONSTRAINT [FK_ReferralRequest_ReasonReference_Entity];

ALTER TABLE [dbo].[Immunization] WITH CHECK CHECK CONSTRAINT [FK__Immunizat__React__74AE54BC];

ALTER TABLE [dbo].[Immunization] WITH CHECK CHECK CONSTRAINT [FK__Immunizat__Subje__6FE99F9F];

ALTER TABLE [dbo].[ReferralRequest] WITH CHECK CHECK CONSTRAINT [FK_ReferralRequest_Patient];

ALTER TABLE [dbo].[MedicationStatement] WITH CHECK CHECK CONSTRAINT [FK__Medicatio__Patie__3E1D39E1];

ALTER TABLE [dbo].[Composition] WITH CHECK CHECK CONSTRAINT [FK_Compositio_Patient];

ALTER TABLE [dbo].[Encounter] WITH CHECK CHECK CONSTRAINT [FK__Encounter__Patie__412EB0B6];

ALTER TABLE [dbo].[Patient] WITH CHECK CHECK CONSTRAINT [FK_Patient_Organization];

ALTER TABLE [dbo].[Patient_Address] WITH CHECK CHECK CONSTRAINT [FK_Patient_Address_Patient];

ALTER TABLE [dbo].[Patient] WITH CHECK CHECK CONSTRAINT [FK_Patient_Patient];

ALTER TABLE [dbo].[Patient_Links] WITH CHECK CHECK CONSTRAINT [FK_Patient_Links_Patient];

ALTER TABLE [dbo].[ProcedureRequest] WITH CHECK CHECK CONSTRAINT [FK_ProcedureRequest_Subject];

ALTER TABLE [dbo].[Condition] WITH CHECK CHECK CONSTRAINT [FK__Condition__Subje__40F9A68C];

ALTER TABLE [dbo].[Patient] WITH CHECK CHECK CONSTRAINT [FK_Patient_Practicioner];

ALTER TABLE [dbo].[Patient] WITH CHECK CHECK CONSTRAINT [FK_Patient_Organization1];

ALTER TABLE [dbo].[Patient_Links] WITH CHECK CHECK CONSTRAINT [FK_Patient_Links_Patient1];

ALTER TABLE [dbo].[AllergyIntollerance] WITH CHECK CHECK CONSTRAINT [FK__AllergyIn__Subje__2CF2ADDF];

ALTER TABLE [dbo].[MedicationRequest] WITH CHECK CHECK CONSTRAINT [FK__Medicatio__Patie__3A4CA8FD];

ALTER TABLE [dbo].[Patient_Contacts] WITH CHECK CHECK CONSTRAINT [FK_Patient_Contacts_Patient];

ALTER TABLE [dbo].[AllergyIntollerance] WITH CHECK CHECK CONSTRAINT [FK__AllergyIn__NoteA__31B762FC];


GO
CREATE TABLE [#__checkStatus] (
    id           INT            IDENTITY (1, 1) PRIMARY KEY CLUSTERED,
    [Schema]     NVARCHAR (256),
    [Table]      NVARCHAR (256),
    [Constraint] NVARCHAR (256)
);

SET NOCOUNT ON;

DECLARE tableconstraintnames CURSOR LOCAL FORWARD_ONLY
    FOR SELECT SCHEMA_NAME([schema_id]),
               OBJECT_NAME([parent_object_id]),
               [name],
               0
        FROM   [sys].[objects]
        WHERE  [parent_object_id] IN (OBJECT_ID(N'dbo.Specimen'), OBJECT_ID(N'dbo.ActivityDefinition'), OBJECT_ID(N'dbo.DiagnosticReport'), OBJECT_ID(N'dbo.Observation'))
               AND [type] IN (N'F', N'C')
                   AND [object_id] IN (SELECT [object_id]
                                       FROM   [sys].[check_constraints]
                                       WHERE  [is_not_trusted] <> 0
                                              AND [is_disabled] = 0
                                       UNION
                                       SELECT [object_id]
                                       FROM   [sys].[foreign_keys]
                                       WHERE  [is_not_trusted] <> 0
                                              AND [is_disabled] = 0);

DECLARE @schemaname AS NVARCHAR (256);

DECLARE @tablename AS NVARCHAR (256);

DECLARE @checkname AS NVARCHAR (256);

DECLARE @is_not_trusted AS INT;

DECLARE @statement AS NVARCHAR (1024);

BEGIN TRY
    OPEN tableconstraintnames;
    FETCH tableconstraintnames INTO @schemaname, @tablename, @checkname, @is_not_trusted;
    WHILE @@fetch_status = 0
        BEGIN
            PRINT N'Checking constraint: ' + @checkname + N' [' + @schemaname + N'].[' + @tablename + N']';
            SET @statement = N'ALTER TABLE [' + @schemaname + N'].[' + @tablename + N'] WITH ' + CASE @is_not_trusted WHEN 0 THEN N'CHECK' ELSE N'NOCHECK' END + N' CHECK CONSTRAINT [' + @checkname + N']';
            BEGIN TRY
                EXECUTE [sp_executesql] @statement;
            END TRY
            BEGIN CATCH
                INSERT  [#__checkStatus] ([Schema], [Table], [Constraint])
                VALUES                  (@schemaname, @tablename, @checkname);
            END CATCH
            FETCH tableconstraintnames INTO @schemaname, @tablename, @checkname, @is_not_trusted;
        END
END TRY
BEGIN CATCH
    PRINT ERROR_MESSAGE();
END CATCH

IF CURSOR_STATUS(N'LOCAL', N'tableconstraintnames') >= 0
    CLOSE tableconstraintnames;

IF CURSOR_STATUS(N'LOCAL', N'tableconstraintnames') = -1
    DEALLOCATE tableconstraintnames;

SELECT N'Constraint verification failed:' + [Schema] + N'.' + [Table] + N',' + [Constraint]
FROM   [#__checkStatus];

IF @@ROWCOUNT > 0
    BEGIN
        DROP TABLE [#__checkStatus];
        RAISERROR (N'An error occurred while verifying constraints', 16, 127);
    END
>>>>>>> Stashed changes

SET NOCOUNT OFF;

DROP TABLE [#__checkStatus];


GO
PRINT N'Update complete.';


GO
