/*
Deployment script for GPData

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar RunAutomatedScripts "false"
:setvar DatabaseName "GPData"
:setvar DefaultFilePrefix "GPData"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO

IF (DB_ID(N'$(DatabaseName)') IS NOT NULL)
BEGIN
    DECLARE @rc      int,                       -- return code
            @fn      nvarchar(4000),            -- file name for back up
            @dir     nvarchar(4000)             -- backup directory

    EXEC @rc = [master].[dbo].[xp_instance_regread] N'HKEY_LOCAL_MACHINE', N'Software\Microsoft\MSSQLServer\MSSQLServer', N'BackupDirectory', @dir output, 'no_output'
    if (@rc = 0) SELECT @dir = @dir + N'\'

    IF (@dir IS NULL)
    BEGIN 
        EXEC @rc = [master].[dbo].[xp_instance_regread] N'HKEY_LOCAL_MACHINE', N'Software\Microsoft\MSSQLServer\MSSQLServer', N'DefaultData', @dir output, 'no_output'
        if (@rc = 0) SELECT @dir = @dir + N'\'
    END

    IF (@dir IS NULL)
    BEGIN
        EXEC @rc = [master].[dbo].[xp_instance_regread] N'HKEY_LOCAL_MACHINE', N'Software\Microsoft\MSSQLServer\Setup', N'SQLDataRoot', @dir output, 'no_output'
        if (@rc = 0) SELECT @dir = @dir + N'\Backup\'
    END

    IF (@dir IS NULL)
    BEGIN
        SELECT @dir = N'$(DefaultDataPath)'
    END

    SELECT  @fn = @dir + N'$(DatabaseName)' + N'-' + 
            CONVERT(nchar(8), GETDATE(), 112) + N'-' + 
            RIGHT(N'0' + RTRIM(CONVERT(nchar(2), DATEPART(hh, GETDATE()))), 2) + 
            RIGHT(N'0' + RTRIM(CONVERT(nchar(2), DATEPART(mi, getdate()))), 2) + 
            RIGHT(N'0' + RTRIM(CONVERT(nchar(2), DATEPART(ss, getdate()))), 2) + 
            N'.bak' 
            BACKUP DATABASE [$(DatabaseName)] TO DISK = @fn
END
GO
USE [$(DatabaseName)];


GO
PRINT N'Dropping Foreign Key [dbo].[FK__Condition__Subje__40F9A68C]...';


GO
ALTER TABLE [dbo].[Condition] DROP CONSTRAINT [FK__Condition__Subje__40F9A68C];


GO
PRINT N'Dropping Foreign Key [dbo].[FK__Condition__Ident__3D2915A8]...';


GO
ALTER TABLE [dbo].[Condition] DROP CONSTRAINT [FK__Condition__Ident__3D2915A8];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_Condition_RelatedClinicalConditions_Condition]...';


GO
ALTER TABLE [dbo].[Condition_RelatedClinicalConditions] DROP CONSTRAINT [FK_Condition_RelatedClinicalConditions_Condition];


GO
PRINT N'Dropping Foreign Key [dbo].[FK__Condition__Actua__3E1D39E1]...';


GO
ALTER TABLE [dbo].[Condition] DROP CONSTRAINT [FK__Condition__Actua__3E1D39E1];


GO
PRINT N'Dropping Foreign Key [dbo].[FK__Condition__NoteA__43D61337]...';


GO
ALTER TABLE [dbo].[Condition] DROP CONSTRAINT [FK__Condition__NoteA__43D61337];


GO
PRINT N'Dropping Foreign Key [dbo].[FK__Condition__Asser__42E1EEFE]...';


GO
ALTER TABLE [dbo].[Condition] DROP CONSTRAINT [FK__Condition__Asser__42E1EEFE];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_Condition_RelatedProblems_Condition]...';


GO
ALTER TABLE [dbo].[Condition_RelatedProblems] DROP CONSTRAINT [FK_Condition_RelatedProblems_Condition];


GO
PRINT N'Dropping Foreign Key [dbo].[FK__Condition__Conte__41EDCAC5]...';


GO
ALTER TABLE [dbo].[Condition] DROP CONSTRAINT [FK__Condition__Conte__41EDCAC5];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_Condition_Evidence_Condition]...';


GO
ALTER TABLE [dbo].[Condition_Evidence] DROP CONSTRAINT [FK_Condition_Evidence_Condition];


GO
/*
The column [dbo].[Condition].[EntityId] on table [dbo].[Condition] must be added, but the column has no default value and does not allow NULL values. If the table contains data, the ALTER script will not work. To avoid this issue you must either: add a default value to the column, mark it as allowing NULL values, or enable the generation of smart-defaults as a deployment option.

The column [dbo].[Condition].[OriginalId] on table [dbo].[Condition] must be added, but the column has no default value and does not allow NULL values. If the table contains data, the ALTER script will not work. To avoid this issue you must either: add a default value to the column, mark it as allowing NULL values, or enable the generation of smart-defaults as a deployment option.

The type for column Code in table [dbo].[Condition] is currently  NVARCHAR (MAX) NULL but is being changed to  UNIQUEIDENTIFIER NULL. Data loss could occur and deployment may fail if the column contains data that is incompatible with type  UNIQUEIDENTIFIER NULL.
*/
GO
PRINT N'Starting rebuilding table [dbo].[Condition]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_Condition] (
    [Id]                   UNIQUEIDENTIFIER NOT NULL,
    [OriginalId]           NVARCHAR (255)   NOT NULL,
    [Identifier]           UNIQUEIDENTIFIER NULL,
    [ActualProblem]        UNIQUEIDENTIFIER NULL,
    [ProblemSignificance]  NVARCHAR (MAX)   NULL,
    [Episode]              NVARCHAR (MAX)   NULL,
    [ClinicalStatus]       NVARCHAR (MAX)   NULL,
    [VerificationStatus]   NVARCHAR (MAX)   NULL,
    [Severity]             NVARCHAR (MAX)   NULL,
    [Code]                 UNIQUEIDENTIFIER NULL,
    [BodySite]             NVARCHAR (MAX)   NULL,
    [Subject]              UNIQUEIDENTIFIER NULL,
    [Context]              UNIQUEIDENTIFIER NULL,
    [OnsetDate]            DATETIME         NULL,
    [OnsetAge]             DECIMAL (18, 2)  NULL,
    [OnsetPeriodStart]     DATETIME         NULL,
    [OnsetPeriodEnd]       DATETIME         NULL,
    [AbatementDate]        DATETIME         NULL,
    [AbatementAge]         DECIMAL (18, 2)  NULL,
    [AbatementPeriodStart] DATETIME         NULL,
    [AbatementPeriodEnd]   DATETIME         NULL,
    [Abatement]            BIT              NULL,
    [AssertedDate]         DATETIME         NOT NULL,
    [Asserter]             UNIQUEIDENTIFIER NOT NULL,
    [EvidenceCodes]        NVARCHAR (MAX)   NULL,
    [NoteText]             NVARCHAR (MAX)   NULL,
    [NoteAuthored]         DATETIME         NULL,
    [NoteAuthor]           UNIQUEIDENTIFIER NULL,
    [EntityId]             UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK__Conditio__A2B5777CD924092C1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[Condition])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_Condition] ([Id], [Identifier], [ActualProblem], [ProblemSignificance], [Episode], [ClinicalStatus], [VerificationStatus], [Severity], [Code], [BodySite], [Subject], [Context], [OnsetDate], [OnsetAge], [OnsetPeriodStart], [OnsetPeriodEnd], [AbatementDate], [AbatementAge], [AbatementPeriodStart], [AbatementPeriodEnd], [Abatement], [AssertedDate], [Asserter], [EvidenceCodes], [NoteText], [NoteAuthored], [NoteAuthor])
        SELECT   [Id],
                 [Identifier],
                 [ActualProblem],
                 [ProblemSignificance],
                 [Episode],
                 [ClinicalStatus],
                 [VerificationStatus],
                 [Severity],
                 [Code],
                 [BodySite],
                 [Subject],
                 [Context],
                 [OnsetDate],
                 [OnsetAge],
                 [OnsetPeriodStart],
                 [OnsetPeriodEnd],
                 [AbatementDate],
                 [AbatementAge],
                 [AbatementPeriodStart],
                 [AbatementPeriodEnd],
                 [Abatement],
                 [AssertedDate],
                 [Asserter],
                 [EvidenceCodes],
                 [NoteText],
                 [NoteAuthored],
                 [NoteAuthor]
        FROM     [dbo].[Condition]
        ORDER BY [Id] ASC;
    END

DROP TABLE [dbo].[Condition];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_Condition]', N'Condition';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK__Conditio__A2B5777CD924092C1]', N'PK__Conditio__A2B5777CD924092C', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating Foreign Key [dbo].[FK__Condition__Subje__40F9A68C]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[Condition] WITH NOCHECK
    ADD CONSTRAINT [FK__Condition__Subje__40F9A68C] FOREIGN KEY ([Subject]) REFERENCES [dbo].[Patient] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Condition__Ident__3D2915A8]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[Condition] WITH NOCHECK
    ADD CONSTRAINT [FK__Condition__Ident__3D2915A8] FOREIGN KEY ([Identifier]) REFERENCES [dbo].[Identifier] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Condition_RelatedClinicalConditions_Condition]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[Condition_RelatedClinicalConditions] WITH NOCHECK
    ADD CONSTRAINT [FK_Condition_RelatedClinicalConditions_Condition] FOREIGN KEY ([ConditionId]) REFERENCES [dbo].[Condition] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Condition__Actua__3E1D39E1]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[Condition] WITH NOCHECK
    ADD CONSTRAINT [FK__Condition__Actua__3E1D39E1] FOREIGN KEY ([ActualProblem]) REFERENCES [dbo].[Entity] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Condition__NoteA__43D61337]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[Condition] WITH NOCHECK
    ADD CONSTRAINT [FK__Condition__NoteA__43D61337] FOREIGN KEY ([NoteAuthor]) REFERENCES [dbo].[Entity] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Condition__Asser__42E1EEFE]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[Condition] WITH NOCHECK
    ADD CONSTRAINT [FK__Condition__Asser__42E1EEFE] FOREIGN KEY ([Asserter]) REFERENCES [dbo].[Practicioner] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Condition_RelatedProblems_Condition]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[Condition_RelatedProblems] WITH NOCHECK
    ADD CONSTRAINT [FK_Condition_RelatedProblems_Condition] FOREIGN KEY ([ConditionId]) REFERENCES [dbo].[Condition] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Condition__Conte__41EDCAC5]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[Condition] WITH NOCHECK
    ADD CONSTRAINT [FK__Condition__Conte__41EDCAC5] FOREIGN KEY ([Context]) REFERENCES [dbo].[Encounter] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Condition_Evidence_Condition]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[Condition_Evidence] WITH NOCHECK
    ADD CONSTRAINT [FK_Condition_Evidence_Condition] FOREIGN KEY ([ConditionId]) REFERENCES [dbo].[Condition] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Condition__Code]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[Condition] WITH NOCHECK
    ADD CONSTRAINT [FK__Condition__Code] FOREIGN KEY ([Code]) REFERENCES [dbo].[Coding] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Condition__Entity]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[Condition] WITH NOCHECK
    ADD CONSTRAINT [FK__Condition__Entity] FOREIGN KEY ([EntityId]) REFERENCES [dbo].[Entity] ([Id]);


GO
BEGIN
	-- Disable constraints for all tables:
	EXEC sp_msforeachtable 'ALTER TABLE ? NOCHECK CONSTRAINT all'
    DELETE FROM [dbo].[EntityType]
	INSERT [dbo].[EntityType] ([EntityType], [EntityName]) VALUES (1,N'Organization')
	INSERT [dbo].[EntityType] ([EntityType], [EntityName]) VALUES (2,N'Location')
	INSERT [dbo].[EntityType] ([EntityType], [EntityName]) VALUES (3,N'Patient')
	INSERT [dbo].[EntityType] ([EntityType], [EntityName]) VALUES (4,N'Practitioner')
	INSERT [dbo].[EntityType] ([EntityType], [EntityName]) VALUES (5,N'Observation')
	INSERT [dbo].[EntityType] ([EntityType], [EntityName]) VALUES (6,N'Condition')
	-- Re-enable constraints for all tables:
	EXEC sp_msforeachtable 'ALTER TABLE ? WITH CHECK CHECK CONSTRAINT all';	
END 
GO

GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[Condition] WITH CHECK CHECK CONSTRAINT [FK__Condition__Subje__40F9A68C];

ALTER TABLE [dbo].[Condition] WITH CHECK CHECK CONSTRAINT [FK__Condition__Ident__3D2915A8];

ALTER TABLE [dbo].[Condition_RelatedClinicalConditions] WITH CHECK CHECK CONSTRAINT [FK_Condition_RelatedClinicalConditions_Condition];

ALTER TABLE [dbo].[Condition] WITH CHECK CHECK CONSTRAINT [FK__Condition__Actua__3E1D39E1];

ALTER TABLE [dbo].[Condition] WITH CHECK CHECK CONSTRAINT [FK__Condition__NoteA__43D61337];

ALTER TABLE [dbo].[Condition] WITH CHECK CHECK CONSTRAINT [FK__Condition__Asser__42E1EEFE];

ALTER TABLE [dbo].[Condition_RelatedProblems] WITH CHECK CHECK CONSTRAINT [FK_Condition_RelatedProblems_Condition];

ALTER TABLE [dbo].[Condition] WITH CHECK CHECK CONSTRAINT [FK__Condition__Conte__41EDCAC5];

ALTER TABLE [dbo].[Condition_Evidence] WITH CHECK CHECK CONSTRAINT [FK_Condition_Evidence_Condition];

ALTER TABLE [dbo].[Condition] WITH CHECK CHECK CONSTRAINT [FK__Condition__Code];

ALTER TABLE [dbo].[Condition] WITH CHECK CHECK CONSTRAINT [FK__Condition__Entity];


GO
PRINT N'Update complete.';


GO
